export const Navbardata=[
    {
        id:1,
        Name:"Home",
        url:"/"
    },
    {
        id:2,
        Name:"Docs",
        url:"https://docs.google.com/document/d/1LQ9r118aYkt3kFbwmZO3Wq7m7BRgxyZS/edit"
    },
    {
        id:3,
        Name:"GitHub",
        url:"https://github.com/patelsatyamgit/DataDrivenReactApp"
    },
    {
        id:4,
        Name:"Demo",
        url:"/demo"
    }
]